# HOW TO USE
# Make a copy of this file named config.yaml with your required edits.
# If there are attributes you do not want, simply comment them out.
# Be sure to read all the comments below.

# Login information
domain: "DOMAIN"
server: "SERVER"
username: "USERNAME"
password: "PASSWORD"

# Export type: CSV, XLSX, or BOTH
export_type: BOTH

# Base DN
base_dn: 'DC=DOMAIN,DC=com'

# File outputs. Defaults to current directory unless you uncommend and add path below.
# output_directory: E:\

# Debug
DEBUG: false

# Event log query string
lockouts_query: "SELECT * FROM Win32_NTLogEvent WHERE Logfile='Security' AND EventCode='4740'"

# Required attributes. These will be in order they are listed, see additional comments below for more details.
# Any attributes NOT listed here MAY break the script, depending on the type of data the attribute is. Add attributes with caution. Any issues will require refactoring of code.

# User specific.
user_attributes:
  - "sAMAccountName"
  - "userAccountControl"  # Account_Disabled, Pwd_Not_Required, Pwd_Cant_Change, Pwd_Doesnt_Expire. Sorting will be like this for this item.
  - "displayName"
  - "msDS-parentdistname"
  - "description"
  - "memberOf"
  - "pwdLastSet"
  - "createTimeStamp"
  - "modifyTimeStamp"
  - "accountExpires"
  - "lastLogon"
  
#Computer specific.
comp_attributes:
  - "sAMAccountName"
  - "userAccountControl"  # Account_Disabled, Pwd_Not_Required, Pwd_Cant_Change, Pwd_Doesnt_Expire. Sorting will be like this for this item.
  - "displayName"
  - "msDS-parentdistname"
  - "description"
  - "pwdLastSet"
  - "createTimeStamp"
  - "modifyTimeStamp"
  - "accountExpires"
  - "lastLogon"
  - "operatingSystem"

# Group specific.
group_attributes:
  - "name"
  - "msDS-parentdistname"
  - "description"
  - "groupType"
  - "member"
  - "createTimeStamp"
  - "modifyTimeStamp"


# Event log query string
lockouts_query: "SELECT * FROM Win32_NTLogEvent WHERE Logfile='Security' AND EventCode='4740'"