
# Login information
domain: "DOMAIN"
server: "SERVER"
username: "USERNAME"
password: "PASSWORD"

# Export type: CSV, XLSX, or BOTH
export_type: BOTH

# Base DN
base_dn: 'DC=DOMAIN,DC=com'

# File outputs
# output_directory: E:\

# Debug
DEBUG: false

# Regex to match the CN= part of example: 'CN=example_cn,OU=example_ou2,OU=example_ou1,DC=dc,DC=domain,DC=com'
"cn_pattern": r"CN=([^,]+)"

# Required attributes. These will be in order they are listed, see additional comments below for more details.
user_attributes:
  - "sAMAccountName"
  - "userAccountControl"  # This attribute contains various details: Account_Disabled, Pwd_Not_Required, Pwd_Cant_Change, Pwd_Doesnt_Expire. In this order.
  - "displayName"
  - "msDS-parentdistname"
  - "description"
  - "memberOf"
  - "pwdLastSet"
  - "createTimeStamp"
  - "modifyTimeStamp"
  - "accountExpires"
  - "lastLogon"
  

comp_attributes:
  - "sAMAccountName"
  - "userAccountControl"  # This attribute contains various details: Account_Disabled, Pwd_Not_Required, Pwd_Cant_Change, Pwd_Doesnt_Expire. In this order.
  - "displayName"
  - "msDS-parentdistname"
  - "description"
  - "pwdLastSet"
  - "createTimeStamp"
  - "modifyTimeStamp"
  - "accountExpires"
  - "lastLogon"
  - "operatingSystem"

group_attributes:
  - "name"
  - "msDS-parentdistname"
  - "description"
  - "groupType"
  - "member"
  - "createTimeStamp"
  - "modifyTimeStamp"